# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Oscilloscope_control.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.W_onglets = QtWidgets.QTabWidget(self.centralwidget)
        self.W_onglets.setGeometry(QtCore.QRect(-4, -1, 541, 511))
        self.W_onglets.setObjectName("W_onglets")
        self.acq_tab = QtWidgets.QWidget()
        self.acq_tab.setObjectName("acq_tab")
        self.Vertical = QtWidgets.QGroupBox(self.acq_tab)
        self.Vertical.setGeometry(QtCore.QRect(20, 210, 481, 261))
        self.Vertical.setObjectName("Vertical")
        self.layoutWidget = QtWidgets.QWidget(self.Vertical)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 431, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.channel1 = QtWidgets.QGroupBox(self.layoutWidget)
        self.channel1.setCheckable(True)
        self.channel1.setObjectName("channel1")
        self.layoutWidget_4 = QtWidgets.QWidget(self.channel1)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 40, 178, 48))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_ch1_pos = QtWidgets.QLabel(self.layoutWidget_4)
        self.lbl_ch1_pos.setObjectName("lbl_ch1_pos")
        self.gridLayout.addWidget(self.lbl_ch1_pos, 0, 0, 1, 1)
        self.ch1_pos = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.ch1_pos.setObjectName("ch1_pos")
        self.gridLayout.addWidget(self.ch1_pos, 0, 1, 1, 1)
        self.lbl_ch1_sca = QtWidgets.QLabel(self.layoutWidget_4)
        self.lbl_ch1_sca.setObjectName("lbl_ch1_sca")
        self.gridLayout.addWidget(self.lbl_ch1_sca, 1, 0, 1, 1)
        self.ch1_sca = QtWidgets.QComboBox(self.layoutWidget_4)
        self.ch1_sca.setAccessibleName("")
        self.ch1_sca.setObjectName("ch1_sca")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.ch1_sca.addItem("")
        self.gridLayout.addWidget(self.ch1_sca, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.channel1, 0, 0, 1, 1)
        self.channel2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.channel2.setCheckable(True)
        self.channel2.setObjectName("channel2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.channel2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(18, 40, 178, 48))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_ch2_pos = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbl_ch2_pos.setObjectName("lbl_ch2_pos")
        self.gridLayout_2.addWidget(self.lbl_ch2_pos, 0, 0, 1, 1)
        self.ch2_pos = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.ch2_pos.setObjectName("ch2_pos")
        self.gridLayout_2.addWidget(self.ch2_pos, 0, 1, 1, 1)
        self.lbl_ch2_sca = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbl_ch2_sca.setObjectName("lbl_ch2_sca")
        self.gridLayout_2.addWidget(self.lbl_ch2_sca, 1, 0, 1, 1)
        self.ch2_sca = QtWidgets.QComboBox(self.layoutWidget_3)
        self.ch2_sca.setAccessibleName("")
        self.ch2_sca.setObjectName("ch2_sca")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.ch2_sca.addItem("")
        self.gridLayout_2.addWidget(self.ch2_sca, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.channel2, 0, 1, 1, 1)
        self.channel3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.channel3.setCheckable(True)
        self.channel3.setObjectName("channel3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.channel3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(18, 40, 178, 48))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_ch3_pos = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_ch3_pos.setObjectName("lbl_ch3_pos")
        self.gridLayout_3.addWidget(self.lbl_ch3_pos, 0, 0, 1, 1)
        self.ch3_pos = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ch3_pos.setObjectName("ch3_pos")
        self.gridLayout_3.addWidget(self.ch3_pos, 0, 1, 1, 1)
        self.lbl_ch3_sca = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_ch3_sca.setObjectName("lbl_ch3_sca")
        self.gridLayout_3.addWidget(self.lbl_ch3_sca, 1, 0, 1, 1)
        self.ch3_sca = QtWidgets.QComboBox(self.layoutWidget_2)
        self.ch3_sca.setAccessibleName("")
        self.ch3_sca.setObjectName("ch3_sca")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.ch3_sca.addItem("")
        self.gridLayout_3.addWidget(self.ch3_sca, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.channel3, 1, 0, 1, 1)
        self.channel4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.channel4.setCheckable(True)
        self.channel4.setObjectName("channel4")
        self.layoutWidget_5 = QtWidgets.QWidget(self.channel4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(18, 40, 178, 48))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_ch4_pos = QtWidgets.QLabel(self.layoutWidget_5)
        self.lbl_ch4_pos.setObjectName("lbl_ch4_pos")
        self.gridLayout_4.addWidget(self.lbl_ch4_pos, 0, 0, 1, 1)
        self.ch4_pos = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.ch4_pos.setObjectName("ch4_pos")
        self.gridLayout_4.addWidget(self.ch4_pos, 0, 1, 1, 1)
        self.lbl_ch4_sca = QtWidgets.QLabel(self.layoutWidget_5)
        self.lbl_ch4_sca.setObjectName("lbl_ch4_sca")
        self.gridLayout_4.addWidget(self.lbl_ch4_sca, 1, 0, 1, 1)
        self.ch4_sca = QtWidgets.QComboBox(self.layoutWidget_5)
        self.ch4_sca.setAccessibleName("")
        self.ch4_sca.setObjectName("ch4_sca")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.ch4_sca.addItem("")
        self.gridLayout_4.addWidget(self.ch4_sca, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.channel4, 1, 1, 1, 1)
        self.Horizontal = QtWidgets.QGroupBox(self.acq_tab)
        self.Horizontal.setGeometry(QtCore.QRect(20, 40, 241, 161))
        self.Horizontal.setObjectName("Horizontal")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Horizontal)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 40, 191, 74))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbl_hor_pos = QtWidgets.QLabel(self.layoutWidget_6)
        self.lbl_hor_pos.setObjectName("lbl_hor_pos")
        self.gridLayout_5.addWidget(self.lbl_hor_pos, 0, 0, 1, 1)
        self.hor_pos = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.hor_pos.setObjectName("hor_pos")
        self.gridLayout_5.addWidget(self.hor_pos, 0, 1, 1, 1)
        self.lbl_hor_sca = QtWidgets.QLabel(self.layoutWidget_6)
        self.lbl_hor_sca.setObjectName("lbl_hor_sca")
        self.gridLayout_5.addWidget(self.lbl_hor_sca, 1, 0, 1, 1)
        self.hor_sca = QtWidgets.QComboBox(self.layoutWidget_6)
        self.hor_sca.setObjectName("hor_sca")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.hor_sca.addItem("")
        self.gridLayout_5.addWidget(self.hor_sca, 1, 1, 1, 1)
        self.lbl_hor_res = QtWidgets.QLabel(self.layoutWidget_6)
        self.lbl_hor_res.setObjectName("lbl_hor_res")
        self.gridLayout_5.addWidget(self.lbl_hor_res, 2, 0, 1, 1)
        self.hor_res = QtWidgets.QComboBox(self.layoutWidget_6)
        self.hor_res.setObjectName("hor_res")
        self.gridLayout_5.addWidget(self.hor_res, 2, 1, 1, 1)
        self.Trigger = QtWidgets.QGroupBox(self.acq_tab)
        self.Trigger.setGeometry(QtCore.QRect(280, 40, 221, 161))
        self.Trigger.setObjectName("Trigger")
        self.layoutWidget1 = QtWidgets.QWidget(self.Trigger)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 182, 126))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.trig_lvl = QtWidgets.QLineEdit(self.layoutWidget1)
        self.trig_lvl.setObjectName("trig_lvl")
        self.gridLayout_6.addWidget(self.trig_lvl, 3, 1, 1, 1)
        self.lbl_trig_sou = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_trig_sou.setObjectName("lbl_trig_sou")
        self.gridLayout_6.addWidget(self.lbl_trig_sou, 0, 0, 1, 1)
        self.trig_cou = QtWidgets.QComboBox(self.layoutWidget1)
        self.trig_cou.setAccessibleName("")
        self.trig_cou.setObjectName("trig_cou")
        self.trig_cou.addItem("")
        self.trig_cou.addItem("")
        self.gridLayout_6.addWidget(self.trig_cou, 1, 1, 1, 1)
        self.lbl_trig_lvl = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_trig_lvl.setObjectName("lbl_trig_lvl")
        self.gridLayout_6.addWidget(self.lbl_trig_lvl, 3, 0, 1, 1)
        self.trig_slo = QtWidgets.QComboBox(self.layoutWidget1)
        self.trig_slo.setAccessibleName("")
        self.trig_slo.setObjectName("trig_slo")
        self.trig_slo.addItem("")
        self.trig_slo.addItem("")
        self.gridLayout_6.addWidget(self.trig_slo, 2, 1, 1, 1)
        self.lbl_trig_slo = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_trig_slo.setObjectName("lbl_trig_slo")
        self.gridLayout_6.addWidget(self.lbl_trig_slo, 2, 0, 1, 1)
        self.trig_sou = QtWidgets.QComboBox(self.layoutWidget1)
        self.trig_sou.setAccessibleName("")
        self.trig_sou.setObjectName("trig_sou")
        self.trig_sou.addItem("")
        self.trig_sou.addItem("")
        self.trig_sou.addItem("")
        self.trig_sou.addItem("")
        self.gridLayout_6.addWidget(self.trig_sou, 0, 1, 1, 1)
        self.lbl_trig_cou = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_trig_cou.setObjectName("lbl_trig_cou")
        self.gridLayout_6.addWidget(self.lbl_trig_cou, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.acq_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(27, 10, 471, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_osc_name = QtWidgets.QLabel(self.layoutWidget2)
        self.lbl_osc_name.setObjectName("lbl_osc_name")
        self.horizontalLayout.addWidget(self.lbl_osc_name)
        self.osc_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.osc_name.setObjectName("osc_name")
        self.horizontalLayout.addWidget(self.osc_name)
        self.W_onglets.addTab(self.acq_tab, "")
        self.wfm_tab = QtWidgets.QWidget()
        self.wfm_tab.setObjectName("wfm_tab")
        self.wfm_grp = QtWidgets.QGroupBox(self.wfm_tab)
        self.wfm_grp.setGeometry(QtCore.QRect(30, 20, 231, 171))
        self.wfm_grp.setObjectName("wfm_grp")
        self.layoutWidget3 = QtWidgets.QWidget(self.wfm_grp)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 188, 119))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.data_encoding = QtWidgets.QComboBox(self.layoutWidget3)
        self.data_encoding.setObjectName("data_encoding")
        self.data_encoding.addItem("")
        self.gridLayout_9.addWidget(self.data_encoding, 2, 1, 1, 1)
        self.data_stop = QtWidgets.QLineEdit(self.layoutWidget3)
        self.data_stop.setEnabled(False)
        self.data_stop.setObjectName("data_stop")
        self.gridLayout_9.addWidget(self.data_stop, 4, 1, 1, 1)
        self.check_data_start = QtWidgets.QCheckBox(self.layoutWidget3)
        self.check_data_start.setObjectName("check_data_start")
        self.gridLayout_9.addWidget(self.check_data_start, 3, 0, 1, 1)
        self.check_data_stop = QtWidgets.QCheckBox(self.layoutWidget3)
        self.check_data_stop.setObjectName("check_data_stop")
        self.gridLayout_9.addWidget(self.check_data_stop, 4, 0, 1, 1)
        self.lbl_data_encoding = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_data_encoding.setObjectName("lbl_data_encoding")
        self.gridLayout_9.addWidget(self.lbl_data_encoding, 2, 0, 1, 1)
        self.data_start = QtWidgets.QLineEdit(self.layoutWidget3)
        self.data_start.setEnabled(False)
        self.data_start.setObjectName("data_start")
        self.gridLayout_9.addWidget(self.data_start, 3, 1, 1, 1)
        self.data_sou = QtWidgets.QComboBox(self.layoutWidget3)
        self.data_sou.setObjectName("data_sou")
        self.data_sou.addItem("")
        self.data_sou.addItem("")
        self.data_sou.addItem("")
        self.data_sou.addItem("")
        self.gridLayout_9.addWidget(self.data_sou, 1, 1, 1, 1)
        self.lbl_data_sou = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_data_sou.setObjectName("lbl_data_sou")
        self.gridLayout_9.addWidget(self.lbl_data_sou, 1, 0, 1, 1)
        self.acq_grp = QtWidgets.QGroupBox(self.wfm_tab)
        self.acq_grp.setGeometry(QtCore.QRect(30, 210, 491, 261))
        self.acq_grp.setCheckable(True)
        self.acq_grp.setChecked(False)
        self.acq_grp.setObjectName("acq_grp")
        self.acq_script = QtWidgets.QComboBox(self.acq_grp)
        self.acq_script.setGeometry(QtCore.QRect(100, 20, 161, 22))
        self.acq_script.setObjectName("acq_script")
        self.parameter_edit = QtWidgets.QTextEdit(self.acq_grp)
        self.parameter_edit.setGeometry(QtCore.QRect(10, 60, 461, 151))
        self.parameter_edit.setObjectName("parameter_edit")
        self.btn_acq = QtWidgets.QPushButton(self.acq_grp)
        self.btn_acq.setGeometry(QtCore.QRect(20, 220, 101, 23))
        self.btn_acq.setObjectName("btn_acq")
        self.lbl_acq_script = QtWidgets.QLabel(self.acq_grp)
        self.lbl_acq_script.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.lbl_acq_script.setObjectName("lbl_acq_script")
        self.progressBar = QtWidgets.QProgressBar(self.acq_grp)
        self.progressBar.setGeometry(QtCore.QRect(130, 220, 341, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.W_onglets.addTab(self.wfm_tab, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.log = QtWidgets.QTextEdit(self.log_tab)
        self.log.setGeometry(QtCore.QRect(20, 10, 491, 471))
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.W_onglets.addTab(self.log_tab, "")
        self.apply_option_grp = QtWidgets.QGroupBox(self.centralwidget)
        self.apply_option_grp.setGeometry(QtCore.QRect(540, 250, 121, 261))
        self.apply_option_grp.setObjectName("apply_option_grp")
        self.layoutWidget4 = QtWidgets.QWidget(self.apply_option_grp)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 91, 88))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_vert_app = QtWidgets.QCheckBox(self.layoutWidget4)
        self.check_vert_app.setChecked(True)
        self.check_vert_app.setObjectName("check_vert_app")
        self.verticalLayout_2.addWidget(self.check_vert_app)
        self.check_hor_app = QtWidgets.QCheckBox(self.layoutWidget4)
        self.check_hor_app.setChecked(True)
        self.check_hor_app.setObjectName("check_hor_app")
        self.verticalLayout_2.addWidget(self.check_hor_app)
        self.check_trig_app = QtWidgets.QCheckBox(self.layoutWidget4)
        self.check_trig_app.setChecked(True)
        self.check_trig_app.setObjectName("check_trig_app")
        self.verticalLayout_2.addWidget(self.check_trig_app)
        self.check_wfm_app = QtWidgets.QCheckBox(self.layoutWidget4)
        self.check_wfm_app.setChecked(True)
        self.check_wfm_app.setObjectName("check_wfm_app")
        self.verticalLayout_2.addWidget(self.check_wfm_app)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(540, 29, 119, 170))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_connect = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout.addWidget(self.btn_connect)
        self.btn_disconnect = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.verticalLayout.addWidget(self.btn_disconnect)
        self.btn_ld_file = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_ld_file.setObjectName("btn_ld_file")
        self.verticalLayout.addWidget(self.btn_ld_file)
        self.btn_ld_osc = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_ld_osc.setObjectName("btn_ld_osc")
        self.verticalLayout.addWidget(self.btn_ld_osc)
        self.btn_save = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        self.btn_apply = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_apply.setObjectName("btn_apply")
        self.verticalLayout.addWidget(self.btn_apply)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 520, 601, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_cmd = QtWidgets.QLabel(self.layoutWidget6)
        self.lbl_cmd.setObjectName("lbl_cmd")
        self.horizontalLayout_2.addWidget(self.lbl_cmd)
        self.cmd_line = QtWidgets.QLineEdit(self.layoutWidget6)
        self.cmd_line.setText("")
        self.cmd_line.setObjectName("cmd_line")
        self.horizontalLayout_2.addWidget(self.cmd_line)
        self.btn_send_cmd = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_send_cmd.setObjectName("btn_send_cmd")
        self.horizontalLayout_2.addWidget(self.btn_send_cmd)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuLoad = QtWidgets.QMenu(self.menuMenu)
        self.menuLoad.setObjectName("menuLoad")
        self.menuOscilloscope = QtWidgets.QMenu(self.menuMenu)
        self.menuOscilloscope.setObjectName("menuOscilloscope")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGPIB_command = QtWidgets.QMenu(self.menuHelp)
        self.menuGPIB_command.setObjectName("menuGPIB_command")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_from_oscilloscope = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_oscilloscope.setObjectName("actionLoad_from_oscilloscope")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_from_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_file.setObjectName("actionLoad_from_file")
        self.actionLoad_from_file_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_file_2.setObjectName("actionLoad_from_file_2")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionAlias_commands = QtWidgets.QAction(MainWindow)
        self.actionAlias_commands.setObjectName("actionAlias_commands")
        self.actionAcquisition = QtWidgets.QAction(MainWindow)
        self.actionAcquisition.setObjectName("actionAcquisition")
        self.actionAlias = QtWidgets.QAction(MainWindow)
        self.actionAlias.setObjectName("actionAlias")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.actionCursor = QtWidgets.QAction(MainWindow)
        self.actionCursor.setObjectName("actionCursor")
        self.actionDiagnostic = QtWidgets.QAction(MainWindow)
        self.actionDiagnostic.setObjectName("actionDiagnostic")
        self.actionDisplay = QtWidgets.QAction(MainWindow)
        self.actionDisplay.setObjectName("actionDisplay")
        self.actionFile_System = QtWidgets.QAction(MainWindow)
        self.actionFile_System.setObjectName("actionFile_System")
        self.actionHardcopy = QtWidgets.QAction(MainWindow)
        self.actionHardcopy.setObjectName("actionHardcopy")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionHorizontal = QtWidgets.QAction(MainWindow)
        self.actionHorizontal.setObjectName("actionHorizontal")
        self.actionMath = QtWidgets.QAction(MainWindow)
        self.actionMath.setObjectName("actionMath")
        self.actionMeasurement = QtWidgets.QAction(MainWindow)
        self.actionMeasurement.setObjectName("actionMeasurement")
        self.actionSave_and_Recall = QtWidgets.QAction(MainWindow)
        self.actionSave_and_Recall.setObjectName("actionSave_and_Recall")
        self.actionTrigger = QtWidgets.QAction(MainWindow)
        self.actionTrigger.setObjectName("actionTrigger")
        self.actionVertical = QtWidgets.QAction(MainWindow)
        self.actionVertical.setObjectName("actionVertical")
        self.actionWaveform_Transfert = QtWidgets.QAction(MainWindow)
        self.actionWaveform_Transfert.setObjectName("actionWaveform_Transfert")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setObjectName("actionZoom")
        self.actionMiscellaneous = QtWidgets.QAction(MainWindow)
        self.actionMiscellaneous.setObjectName("actionMiscellaneous")
        self.actionStatus_and_Error = QtWidgets.QAction(MainWindow)
        self.actionStatus_and_Error.setObjectName("actionStatus_and_Error")
        self.menuLoad.addAction(self.actionLoad_from_file_2)
        self.menuLoad.addAction(self.actionLoad_from_oscilloscope)
        self.menuOscilloscope.addAction(self.actionConnect)
        self.menuOscilloscope.addAction(self.actionDisconnect)
        self.menuMenu.addAction(self.menuOscilloscope.menuAction())
        self.menuMenu.addAction(self.menuLoad.menuAction())
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuit)
        self.menuGPIB_command.addAction(self.actionAcquisition)
        self.menuGPIB_command.addAction(self.actionAlias)
        self.menuGPIB_command.addAction(self.actionCalibrate)
        self.menuGPIB_command.addAction(self.actionCursor)
        self.menuGPIB_command.addAction(self.actionDiagnostic)
        self.menuGPIB_command.addAction(self.actionDisplay)
        self.menuGPIB_command.addAction(self.actionFile_System)
        self.menuGPIB_command.addAction(self.actionHardcopy)
        self.menuGPIB_command.addAction(self.actionHistogram)
        self.menuGPIB_command.addAction(self.actionHorizontal)
        self.menuGPIB_command.addAction(self.actionMath)
        self.menuGPIB_command.addAction(self.actionMeasurement)
        self.menuGPIB_command.addAction(self.actionMiscellaneous)
        self.menuGPIB_command.addAction(self.actionSave_and_Recall)
        self.menuGPIB_command.addAction(self.actionStatus_and_Error)
        self.menuGPIB_command.addAction(self.actionTrigger)
        self.menuGPIB_command.addAction(self.actionVertical)
        self.menuGPIB_command.addAction(self.actionWaveform_Transfert)
        self.menuGPIB_command.addAction(self.actionZoom)
        self.menuHelp.addAction(self.menuGPIB_command.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.W_onglets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Oscilloscope Control"))
        self.Vertical.setTitle(_translate("MainWindow", "Vertical"))
        self.channel1.setTitle(_translate("MainWindow", "Channel 1"))
        self.lbl_ch1_pos.setText(_translate("MainWindow", "Position"))
        self.ch1_pos.setText(_translate("MainWindow", "0"))
        self.lbl_ch1_sca.setText(_translate("MainWindow", "Scale"))
        self.ch1_sca.setItemText(0, _translate("MainWindow", "2.0E-3"))
        self.ch1_sca.setItemText(1, _translate("MainWindow", "5.0E-3"))
        self.ch1_sca.setItemText(2, _translate("MainWindow", "10E-3"))
        self.ch1_sca.setItemText(3, _translate("MainWindow", "20E-3"))
        self.ch1_sca.setItemText(4, _translate("MainWindow", "50E-3"))
        self.ch1_sca.setItemText(5, _translate("MainWindow", "100E-3"))
        self.ch1_sca.setItemText(6, _translate("MainWindow", "200E-3"))
        self.ch1_sca.setItemText(7, _translate("MainWindow", "500E-3"))
        self.ch1_sca.setItemText(8, _translate("MainWindow", "1"))
        self.channel2.setTitle(_translate("MainWindow", "Channel 2"))
        self.lbl_ch2_pos.setText(_translate("MainWindow", "Position"))
        self.ch2_pos.setText(_translate("MainWindow", "0"))
        self.lbl_ch2_sca.setText(_translate("MainWindow", "Scale"))
        self.ch2_sca.setItemText(0, _translate("MainWindow", "2.0E-3"))
        self.ch2_sca.setItemText(1, _translate("MainWindow", "5.0E-3"))
        self.ch2_sca.setItemText(2, _translate("MainWindow", "10E-3"))
        self.ch2_sca.setItemText(3, _translate("MainWindow", "20E-3"))
        self.ch2_sca.setItemText(4, _translate("MainWindow", "50E-3"))
        self.ch2_sca.setItemText(5, _translate("MainWindow", "100E-3"))
        self.ch2_sca.setItemText(6, _translate("MainWindow", "200E-3"))
        self.ch2_sca.setItemText(7, _translate("MainWindow", "500E-3"))
        self.ch2_sca.setItemText(8, _translate("MainWindow", "1"))
        self.channel3.setTitle(_translate("MainWindow", "Channel 3"))
        self.lbl_ch3_pos.setText(_translate("MainWindow", "Position"))
        self.ch3_pos.setText(_translate("MainWindow", "0"))
        self.lbl_ch3_sca.setText(_translate("MainWindow", "Scale"))
        self.ch3_sca.setItemText(0, _translate("MainWindow", "2.0E-3"))
        self.ch3_sca.setItemText(1, _translate("MainWindow", "5.0E-3"))
        self.ch3_sca.setItemText(2, _translate("MainWindow", "10E-3"))
        self.ch3_sca.setItemText(3, _translate("MainWindow", "20E-3"))
        self.ch3_sca.setItemText(4, _translate("MainWindow", "50E-3"))
        self.ch3_sca.setItemText(5, _translate("MainWindow", "100E-3"))
        self.ch3_sca.setItemText(6, _translate("MainWindow", "200E-3"))
        self.ch3_sca.setItemText(7, _translate("MainWindow", "500E-3"))
        self.ch3_sca.setItemText(8, _translate("MainWindow", "1"))
        self.channel4.setTitle(_translate("MainWindow", "Channel 4"))
        self.lbl_ch4_pos.setText(_translate("MainWindow", "Position"))
        self.ch4_pos.setText(_translate("MainWindow", "0"))
        self.lbl_ch4_sca.setText(_translate("MainWindow", "Scale"))
        self.ch4_sca.setItemText(0, _translate("MainWindow", "2.0E-3"))
        self.ch4_sca.setItemText(1, _translate("MainWindow", "5.0E-3"))
        self.ch4_sca.setItemText(2, _translate("MainWindow", "10E-3"))
        self.ch4_sca.setItemText(3, _translate("MainWindow", "20E-3"))
        self.ch4_sca.setItemText(4, _translate("MainWindow", "50E-3"))
        self.ch4_sca.setItemText(5, _translate("MainWindow", "100E-3"))
        self.ch4_sca.setItemText(6, _translate("MainWindow", "200E-3"))
        self.ch4_sca.setItemText(7, _translate("MainWindow", "500E-3"))
        self.ch4_sca.setItemText(8, _translate("MainWindow", "1"))
        self.Horizontal.setTitle(_translate("MainWindow", "Horizontal"))
        self.lbl_hor_pos.setText(_translate("MainWindow", "Position"))
        self.hor_pos.setText(_translate("MainWindow", "0"))
        self.lbl_hor_sca.setText(_translate("MainWindow", "Scale"))
        self.hor_sca.setItemText(0, _translate("MainWindow", "2.5E-9"))
        self.hor_sca.setItemText(1, _translate("MainWindow", "5E-9"))
        self.hor_sca.setItemText(2, _translate("MainWindow", "10E-9"))
        self.hor_sca.setItemText(3, _translate("MainWindow", "20E-9"))
        self.hor_sca.setItemText(4, _translate("MainWindow", "40E-9"))
        self.hor_sca.setItemText(5, _translate("MainWindow", "80E-9"))
        self.hor_sca.setItemText(6, _translate("MainWindow", "200E-9"))
        self.hor_sca.setItemText(7, _translate("MainWindow", "400E-9"))
        self.hor_sca.setItemText(8, _translate("MainWindow", "1E-6"))
        self.hor_sca.setItemText(9, _translate("MainWindow", "2E-6"))
        self.hor_sca.setItemText(10, _translate("MainWindow", "4E-6"))
        self.hor_sca.setItemText(11, _translate("MainWindow", "10E-6"))
        self.hor_sca.setItemText(12, _translate("MainWindow", "20E-6"))
        self.hor_sca.setItemText(13, _translate("MainWindow", "40E-6"))
        self.hor_sca.setItemText(14, _translate("MainWindow", "100E-6"))
        self.hor_sca.setItemText(15, _translate("MainWindow", "200E-6"))
        self.hor_sca.setItemText(16, _translate("MainWindow", "400E-6"))
        self.hor_sca.setItemText(17, _translate("MainWindow", "1E-3"))
        self.hor_sca.setItemText(18, _translate("MainWindow", "2E-3"))
        self.hor_sca.setItemText(19, _translate("MainWindow", "4E-3"))
        self.hor_sca.setItemText(20, _translate("MainWindow", "10E-3"))
        self.hor_sca.setItemText(21, _translate("MainWindow", "20E-3"))
        self.hor_sca.setItemText(22, _translate("MainWindow", "40E-3"))
        self.hor_sca.setItemText(23, _translate("MainWindow", "100E-3"))
        self.hor_sca.setItemText(24, _translate("MainWindow", "200E-3"))
        self.hor_sca.setItemText(25, _translate("MainWindow", "400E-3"))
        self.hor_sca.setItemText(26, _translate("MainWindow", "1"))
        self.hor_sca.setItemText(27, _translate("MainWindow", "2"))
        self.hor_sca.setItemText(28, _translate("MainWindow", "4"))
        self.hor_sca.setItemText(29, _translate("MainWindow", "10"))
        self.hor_sca.setItemText(30, _translate("MainWindow", "20"))
        self.hor_sca.setItemText(31, _translate("MainWindow", "40"))
        self.lbl_hor_res.setText(_translate("MainWindow", "Resolution"))
        self.Trigger.setTitle(_translate("MainWindow", "Trigger"))
        self.trig_lvl.setText(_translate("MainWindow", "0"))
        self.lbl_trig_sou.setText(_translate("MainWindow", "Source"))
        self.trig_cou.setItemText(0, _translate("MainWindow", "DC"))
        self.trig_cou.setItemText(1, _translate("MainWindow", "AC"))
        self.lbl_trig_lvl.setText(_translate("MainWindow", "Level"))
        self.trig_slo.setItemText(0, _translate("MainWindow", "RISe"))
        self.trig_slo.setItemText(1, _translate("MainWindow", "FALL"))
        self.lbl_trig_slo.setText(_translate("MainWindow", "Slope"))
        self.trig_sou.setItemText(0, _translate("MainWindow", "CH1"))
        self.trig_sou.setItemText(1, _translate("MainWindow", "CH2"))
        self.trig_sou.setItemText(2, _translate("MainWindow", "CH3"))
        self.trig_sou.setItemText(3, _translate("MainWindow", "CH4"))
        self.lbl_trig_cou.setText(_translate("MainWindow", "Coupling"))
        self.lbl_osc_name.setText(_translate("MainWindow", "Oscilloscope name"))
        self.osc_name.setText(_translate("MainWindow", "TCPIP::150.197.100.17::gpib0,1::INSTR"))
        self.W_onglets.setTabText(self.W_onglets.indexOf(self.acq_tab), _translate("MainWindow", "Acquisition settup"))
        self.wfm_grp.setTitle(_translate("MainWindow", "Waveform parameters"))
        self.data_encoding.setItemText(0, _translate("MainWindow", "ASCII"))
        self.check_data_start.setText(_translate("MainWindow", "Start"))
        self.check_data_stop.setText(_translate("MainWindow", "Stop"))
        self.lbl_data_encoding.setText(_translate("MainWindow", "Encoding"))
        self.data_start.setText(_translate("MainWindow", "0"))
        self.data_sou.setItemText(0, _translate("MainWindow", "CH1"))
        self.data_sou.setItemText(1, _translate("MainWindow", "CH2"))
        self.data_sou.setItemText(2, _translate("MainWindow", "CH3"))
        self.data_sou.setItemText(3, _translate("MainWindow", "CH4"))
        self.lbl_data_sou.setText(_translate("MainWindow", "Data source"))
        self.acq_grp.setTitle(_translate("MainWindow", "Acquisition"))
        self.btn_acq.setText(_translate("MainWindow", "Start acquisition"))
        self.lbl_acq_script.setText(_translate("MainWindow", "Acquisition Script"))
        self.W_onglets.setTabText(self.W_onglets.indexOf(self.wfm_tab), _translate("MainWindow", "Waveform"))
        self.W_onglets.setTabText(self.W_onglets.indexOf(self.log_tab), _translate("MainWindow", "Log"))
        self.apply_option_grp.setTitle(_translate("MainWindow", "Apply option"))
        self.check_vert_app.setText(_translate("MainWindow", "Vertical"))
        self.check_hor_app.setText(_translate("MainWindow", "Horizontal"))
        self.check_trig_app.setText(_translate("MainWindow", "Trigger"))
        self.check_wfm_app.setText(_translate("MainWindow", "Waveform"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.btn_disconnect.setText(_translate("MainWindow", "disconnect"))
        self.btn_ld_file.setText(_translate("MainWindow", "Load from file"))
        self.btn_ld_osc.setText(_translate("MainWindow", "Load from Oscilloscope"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_apply.setText(_translate("MainWindow", "Apply"))
        self.lbl_cmd.setText(_translate("MainWindow", "Command"))
        self.btn_send_cmd.setText(_translate("MainWindow", "Send"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.menuOscilloscope.setTitle(_translate("MainWindow", "Oscilloscope"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGPIB_command.setTitle(_translate("MainWindow", "GPIB command"))
        self.actionLoad_from_oscilloscope.setText(_translate("MainWindow", "Load from oscilloscope"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad_from_file.setText(_translate("MainWindow", "Load from file"))
        self.actionLoad_from_file_2.setText(_translate("MainWindow", "Load from file"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionAlias_commands.setText(_translate("MainWindow", "Alias commands"))
        self.actionAcquisition.setText(_translate("MainWindow", "Acquisition"))
        self.actionAlias.setText(_translate("MainWindow", "Alias"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))
        self.actionCursor.setText(_translate("MainWindow", "Cursor"))
        self.actionDiagnostic.setText(_translate("MainWindow", "Diagnostic"))
        self.actionDisplay.setText(_translate("MainWindow", "Display"))
        self.actionFile_System.setText(_translate("MainWindow", "File System"))
        self.actionHardcopy.setText(_translate("MainWindow", "Hardcopy"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionHorizontal.setText(_translate("MainWindow", "Horizontal"))
        self.actionMath.setText(_translate("MainWindow", "Math"))
        self.actionMeasurement.setText(_translate("MainWindow", "Measurement"))
        self.actionSave_and_Recall.setText(_translate("MainWindow", "Save and Recall"))
        self.actionTrigger.setText(_translate("MainWindow", "Trigger"))
        self.actionVertical.setText(_translate("MainWindow", "Vertical"))
        self.actionWaveform_Transfert.setText(_translate("MainWindow", "Waveform Transfert"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionMiscellaneous.setText(_translate("MainWindow", "Miscellaneous"))
        self.actionStatus_and_Error.setText(_translate("MainWindow", "Status and Error"))


